site_name: PeiYang Flyer

theme:
  name: material
  custom_dir: overrides

nav:
  - Home: index.md
  - 内容征集: contribution.md
  - 24Fall CSPhD@NUS: christopher.md
  - 24Fall MScISE@NUS: orange.md
  - 24Fall LinguisticsPhD@PolyU: estelle.md
  - 关于交换项目的经验: exchange.md

extra:
  analytics:
    provider: google
    property: G-5GLZT3Q3F6
